Minsk-Boika-Ilya-2/Lab07.UnitTesting/Lab06.MVC/Controllers/CarsController.cs
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Geely.Domain;
using Geely.Services;
using Geely.Services.Interfaces;
using Lab06.MVC.DTO;
using Lab06.MVC.Models.Cars;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lab06.MVC.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICarService _carService;

        private readonly ICarTypeService _carTypeService;

        private readonly IMapper _mapper;

        public CarsController(ICarService carService, ICarTypeService carTypeService, IMapper mapper)
        {
            _carService = carService;
            _carTypeService = carTypeService;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index(string searchText)
        {
            List<Car> cars;

            if (string.IsNullOrWhiteSpace(searchText))
            {
                cars = _carService.GetAllCars();
            }
            else
            {
                cars = _carService.Search(searchText);
            }

            var model = new CarsModel()
            {
                Cars = _mapper.Map<List<CarDto>>(cars),
                SearchText = searchText
            };

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewData["ActionType"] = "Edit";

            var car = _carService.GetById(id);
            var carTypes = _carTypeService.GetAllCarTypes();

            var model = new EditCarModel
            {
                Car = _mapper.Map<CarDto>(car),
                CarTypes = _mapper.Map<List<CarTypeDto>>(carTypes)
            };

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult Edit(EditCarModel model)
        {
            if (ModelState.IsValid)
            {
                var car = _mapper.Map<Car>(model.Car);
                _carService.Save(car);
                return RedirectToAction("Index");
            }

            var carTypes = _carTypeService.GetAllCarTypes();
            model.CarTypes = _mapper.Map<List<CarTypeDto>>(carTypes);

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["ActionType"] = "Create";

            var carTypes = _carTypeService.GetAllCarTypes();

            var model = new EditCarModel
            {
                Car = new CarDto(),
                CarTypes = _mapper.Map<List<CarTypeDto>>(carTypes),
            };

            return View("Edit", model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult Remove(int id)
        {
            _carService.Remove(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Order(int carId)
        {
            if (User.IsInRole("user"))
            {
                var userId = int.Parse(Request.HttpContext.User.Claims.SingleOrDefault(c => c.Type == "Id")?.Value);

                if (_carService.IsCarOrderedByUser(carId, userId))
                {
                    return RedirectToAction("Error", new { error = OrderErrors.CarAlreadyOrdered });
                }

                ViewData["ActionType"] = "Order";

                var model = new AddCarToUserModel
                {
                    CarId = carId,
                    UserId = userId,
                };

                return View(model);
            }

            TempData["shortMessage"] = "You need to log in or register before test-drive ordering";

            return RedirectToAction("Login", "Account");
        }

        [Authorize(Roles = "user")]
        [HttpPost]
        public IActionResult Order(AddCarToUserModel model)
        {
            _carService.AddCarToUser(model.CarId, model.UserId, model.TestdriveDate);
            return RedirectToAction("Index");
        }

        public IActionResult Error(string error)
        {
            ViewBag.ErrorMessage = Errors.GetMessage(error);

            return View();
        }
    }
}

Minsk-Boika-Ilya-2/Lab07.UnitTesting/Lab06.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab06.MVC</title>
    <link rel="stylesheet" href="~/css/common.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <div class="row result-logo">
                        <div class="col-md-1 logo-img" >
                            <img src="@($"/images/cars/Logo.png" ) "  usemap="#map1"  alt="Logo" />
                        </div>
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    @Html.Partial("_LoginPartial")

                    <ul class="nav navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            <div class="container body-content"
                 @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Geely - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>